/**
 * SpotiLIE Playback Module
 *
 * Handles:
 * - Shuffle reseeding for truly random playback
 * - Media action bridge (for notification controls + Bluetooth)
 * - Bluetooth disconnect → auto-pause (JS-side backup for Kotlin receiver)
 * - Surgical storage wipe (shuffle/queue keys only — preserves music cache)
 */

export function initPlaybackHooks() {
  initClickLogger();
  initMediaErrorDiagnostic();
  initMediaActionBridge();
  initNativeMessageListener();
  initBluetoothPauseGuard();
  initMobileTrackClick();
  initStorageWipe();
}

/** Diagnostic logger for HTMLMediaElement errors and play() rejections */
function initMediaErrorDiagnostic() {
  try {
    const origPlay = HTMLMediaElement.prototype.play;
    if (origPlay && !(origPlay as any)._spotilie_patched) {
      const patchedPlay = function(this: HTMLMediaElement) {
        console.log('SpotiLIE: HTMLMediaElement.play() invoked on', this.src || this.currentSrc || 'MSE stream');
        return origPlay.apply(this, arguments as any)
          .then(res => {
            console.log('SpotiLIE: HTMLMediaElement.play() SUCCEEDED');
            return res;
          })
          .catch(err => {
            console.error('SpotiLIE: HTMLMediaElement.play() REJECTED:', err?.name, err?.message, err);
            throw err;
          });
      };
      (patchedPlay as any)._spotilie_patched = true;
      HTMLMediaElement.prototype.play = patchedPlay;
    }

    document.addEventListener('error', (e) => {
      const t = e.target as HTMLElement;
      if (t && (t.tagName === 'AUDIO' || t.tagName === 'VIDEO')) {
        const mediaErr = (t as HTMLMediaElement).error;
        console.error('SpotiLIE: Media Element Error Event:', mediaErr?.code, mediaErr?.message, (t as HTMLMediaElement).src);
      }
    }, true);
  } catch (_) {}
}

/** Diagnostic logger: logs exact DOM target of every user tap/click to logcat */
function initClickLogger() {
  document.addEventListener('click', (e) => {
    const t = e.target as HTMLElement;
    if (t) {
      const info = `${t.tagName}.${(t.className || '').toString().slice(0, 40)} [id=${t.id || ''}] [data-testid=${t.getAttribute('data-testid') || ''}]`;
      console.log('SpotiLIE Click Target:', info);
    }
  }, true);
}

/**
 * Mobile track tap handler.
 * On Desktop Spotify Web Player, single-clicking a track row only selects/highlights it.
 * To play a track on mobile single tap, we find the row's embedded play button or dispatch dblclick.
 */
function initMobileTrackClick() {
  document.addEventListener('click', (e) => {
    // Ignore synthetic .click() calls generated by code to prevent infinite event loops
    if (!e.isTrusted) return;

    const target = e.target as HTMLElement;
    if (!target) return;

    // Do not intercept if user tapped an explicit sub-button or link (e.g. artist link, more options, add to playlist)
    if (target.closest('button, a[href*="/artist/"], a[href*="/album/"], [role="button"], [data-testid="more-button"], [data-testid="add-button"]')) {
      return;
    }

    const row = target.closest('[data-testid="tracklist-row"], [role="row"]') as HTMLElement | null;
    if (!row) return;

    // 1. Find the track's embedded play button
    let playBtn = row.querySelector(
      'button[aria-label*="Play" i], button[aria-label*="play" i], [data-testid="play-button"], [data-testid="row-play-button"], [data-encore-id="buttonPrimary"], [class*="playButton" i]'
    ) as HTMLElement | null;

    if (!playBtn) {
      // Search all buttons in row for play intent
      const buttons = Array.from(row.querySelectorAll('button'));
      playBtn = buttons.find(b => {
        const label = (b.getAttribute('aria-label') || b.getAttribute('data-testid') || b.className || '').toLowerCase();
        return label.includes('play') || label.includes('reproducir');
      }) || null;
    }

    if (playBtn) {
      console.log('SpotiLIE: Track play button clicked via row tap');
      playBtn.click();
      return;
    }

    // 2. Fallback: Find internal track link and click it
    const trackLink = row.querySelector('a[data-testid="internal-track-link"], a[href*="/track/"]') as HTMLElement | null;
    if (trackLink) {
      console.log('SpotiLIE: Clicking internal track link via row tap');
      trackLink.click();
    }
  }, false);
}

function clickSpotifyButton(selectors: string[]): boolean {
  for (const s of selectors) {
    const btn = document.querySelector(s) as HTMLElement | null;
    if (btn) {
      try {
        btn.click();
        console.log(`SpotiLIE: Clicked media button via selector: ${s}`);
        return true;
      } catch (e) {
        console.warn(`SpotiLIE: Failed clicking ${s}:`, e);
      }
    }
  }
  return false;
}

/** Bridge for native notification controls and Kotlin MediaSession → JS click simulation */
function initMediaActionBridge() {
  (window as any).spotilieMediaAction = (action: string) => {
    console.log(`SpotiLIE: spotilieMediaAction executed for action '${action}'`);

    const audio = document.querySelector('audio, video') as HTMLMediaElement | null;

    if (action === 'play') {
      const clicked = clickSpotifyButton([
        'button[data-testid="control-button-playpause"]',
        'button[aria-label*="Play" i]',
        'button[aria-label*="reproducir" i]'
      ]);
      if (!clicked || (audio && audio.paused)) {
        audio?.play().catch(() => {});
      }
    } else if (action === 'pause') {
      const clicked = clickSpotifyButton([
        'button[data-testid="control-button-playpause"]',
        'button[aria-label*="Pause" i]'
      ]);
      if (audio && !audio.paused) audio.pause();
    } else if (action === 'toggle') {
      const clicked = clickSpotifyButton([
        'button[data-testid="control-button-playpause"]'
      ]);
      if (!clicked && audio) {
        if (audio.paused) audio.play().catch(() => {});
        else audio.pause();
      }
    } else if (action === 'next') {
      clickSpotifyButton([
        'button[data-testid="control-button-skip-forward"]',
        'button[aria-label*="Next" i]',
        'button[aria-label*="Siguiente" i]',
        '[data-testid="skip-ad-button"]'
      ]);
    } else if (action === 'prev') {
      clickSpotifyButton([
        'button[data-testid="control-button-skip-back"]',
        'button[aria-label*="Previous" i]',
        'button[aria-label*="Anterior" i]'
      ]);
    }
  };
}

/**
 * JS-side Bluetooth disconnect guard.
 * Backup for the Kotlin BroadcastReceiver in MediaForegroundService.
 * Fires when audio output device changes (e.g. headphones disconnected).
 */
function initBluetoothPauseGuard() {
  try {
    if (!navigator.mediaDevices?.addEventListener) return;

    navigator.mediaDevices.addEventListener('devicechange', () => {
      setTimeout(() => {
        const audio = document.querySelector('audio, video') as HTMLMediaElement | null;
        if (audio && !audio.paused) {
          console.log('SpotiLIE: Audio output device changed/disconnected — pausing playback');
          audio.pause();
          clickSpotifyButton(['button[data-testid="control-button-playpause"]']);
        }
      }, 250);
    });
  } catch (e) {
    console.warn('SpotiLIE: Could not set up Bluetooth pause guard', e);
  }
}

/**
 * Listen for MEDIA_ACTION messages relayed from the background script.
 * This is the primary control path when using the GeckoView native port bridge.
 * background.js receives the native port message and forwards it here via
 * browser.tabs.sendMessage → this listener.
 */
function initNativeMessageListener() {
  try {
    // browser is the WebExtension API — available in GeckoView content scripts
    const ext = (globalThis as any).browser || (globalThis as any).chrome;
    if (!ext?.runtime?.onMessage) return;

    ext.runtime.onMessage.addListener((msg: any) => {
      if (msg?.type === 'MEDIA_ACTION' && typeof msg.action === 'string') {
        console.log('SpotiLIE: MEDIA_ACTION received from native bridge:', msg.action);
        (window as any).spotilieMediaAction?.(msg.action);
        return true;
      }
    });
    console.log('SpotiLIE: Native message listener active');
  } catch (e) {
    console.warn('SpotiLIE: Could not set up native message listener', e);
  }
}

/**
 * JS-side Bluetooth disconnect guard.
 * Backup for the Kotlin BroadcastReceiver in MediaForegroundService.
 * Fires when audio output device changes (e.g. headphones disconnected).
 */
function initBluetoothPauseGuard() {
  try {
    if (!navigator.mediaDevices?.addEventListener) return;

    navigator.mediaDevices.addEventListener('devicechange', () => {
      // Small delay to let the system settle before checking state
      setTimeout(() => {
        // Only pause if we were actually playing
        const pauseBtn = document.querySelector(
          'button[data-testid="control-button-playpause"][aria-label="Pause"]'
        ) as HTMLElement | null;
        if (pauseBtn) {
          console.log('SpotiLIE: Audio device disconnected — pausing playback');
          pauseBtn.click();
        }
      }, 400);
    });
  } catch (e) {
    console.warn('SpotiLIE: Could not set up Bluetooth pause guard', e);
  }
}

/**
 * Storage wipe — DISABLED.
 *
 * Previous approach wiped localStorage keys on every launch to reset shuffle seeds.
 * This inadvertently cleared Spotify's session/auth tokens causing the player to
 * fail to initialize ("music player doesn't work").
 *
 * Shuffle reseeding is handled by the click listener in initShuffleReseed() which
 * fires only when the user actually starts playback — that's sufficient.
 */
function initStorageWipe() {
  // Intentionally empty — do not wipe storage on launch.
}

